# 情報計算科学の基礎 演習2

以下に、ガウスの消去法（ピボットなし）を使って方程式 $Ax=b$ を解くプログラムを示します。ガウスの消去法（ピボットあり）及び共役勾配法を実装し，以下のプログラムを参考に、求解法や方程式を変えて、レポート課題1に取り組んでください。

## ガウスの消去法（ピボットなし）の関数の定義

In [18]:
# Numpy を使うので，Numpy のライブラリーをインポート
import numpy as np

def gausselimination_withoutpivot(n,Aorg,borg):
  A = np.copy(Aorg)
  b = np.copy(borg)
  x = np.zeros(n)

  # 前進消去
  for j in range(0,n,1):
    for i in range(j+1,n,1):
      coe = -A[i][j]/A[j][j]
      for k in range(j,n,1):
        A[i][k]+=coe*A[j][k]
      b[i]+=coe*b[j]

  # 後退代入
  for j in range(n-1,-1,-1):
    btmp=b[j]
    for i in range(n-1,j,-1):
      btmp-=A[j][i]*x[i]
    x[j]=btmp/A[j][j]

  # 結果の出力
  return x

def gausselimination_withpivot(n,A,b):
  x = np.zeros(n)
  Aorg = np.copy(A)
  borg = np.copy(b)

  #前進消去
  for j in range(n):
    #ピポット選択
    if A[j][j] == 0:
      list = [A[i][j] for i in range(j+1,n)]
      abs_list = [abs(i) for i in list]
      m = abs_list.index(max(abs_list))
      p = m + j + 1
      #交換
      b[j],b[p] = b[p],b[j]
      for c in range(n):
        A[j][c],A[p][c] = A[p][c],A[j][c]

    for i in range(j+1,n,1):
      coe=-A[i][j]/A[j][j]
      for k in range(j,n,1):
        A[i][k]+=coe*A[j][k]
      b[i]+=coe*b[j]
    
  #後退代入・結果出力
  for j in range(n-1,-1,-1):
    btmp=b[j]
    for i in range(n-1,j,-1):
      btmp -= A[j][i]*x[i]
    x[j]=btmp/A[j][j]
  return x

## 行列$A$, ベクトル$b$ の設定

In [23]:
n = 9
ds = 1./(n+1)
A = np.zeros((n,n)) #すべての成分が0のn×n行列 
b = np.zeros(n) #すべての成分が0のサイズnのベクトル
for i in range(n):
  A[i][i] = 2./ds
  b[i] = -ds
for i in range(n-1):
  A[i][i+1] = -1./ds
  A[i+1][i] = -1./ds

P = np.array( [[A[n-i-1][j] for j in range(n)] for i in range(n)] )
q = np.array( [b[n-i-1] for i in range(n)] )

print(A)
print(P)

print(b)
print(q)

[[ 20. -10.   0.   0.   0.   0.   0.   0.   0.]
 [-10.  20. -10.   0.   0.   0.   0.   0.   0.]
 [  0. -10.  20. -10.   0.   0.   0.   0.   0.]
 [  0.   0. -10.  20. -10.   0.   0.   0.   0.]
 [  0.   0.   0. -10.  20. -10.   0.   0.   0.]
 [  0.   0.   0.   0. -10.  20. -10.   0.   0.]
 [  0.   0.   0.   0.   0. -10.  20. -10.   0.]
 [  0.   0.   0.   0.   0.   0. -10.  20. -10.]
 [  0.   0.   0.   0.   0.   0.   0. -10.  20.]]
[[  0.   0.   0.   0.   0.   0.   0. -10.  20.]
 [  0.   0.   0.   0.   0.   0. -10.  20. -10.]
 [  0.   0.   0.   0.   0. -10.  20. -10.   0.]
 [  0.   0.   0.   0. -10.  20. -10.   0.   0.]
 [  0.   0.   0. -10.  20. -10.   0.   0.   0.]
 [  0.   0. -10.  20. -10.   0.   0.   0.   0.]
 [  0. -10.  20. -10.   0.   0.   0.   0.   0.]
 [-10.  20. -10.   0.   0.   0.   0.   0.   0.]
 [ 20. -10.   0.   0.   0.   0.   0.   0.   0.]]
[-0.1 -0.1 -0.1 -0.1 -0.1 -0.1 -0.1 -0.1 -0.1]
[-0.1 -0.1 -0.1 -0.1 -0.1 -0.1 -0.1 -0.1 -0.1]


## ガウスの消去法（ピボットなし）で $Ax=b$ を解く

In [20]:
x = gausselimination_withoutpivot(n,A,b)
print(x)

[-0.045 -0.08  -0.105 -0.12  -0.125 -0.12  -0.105 -0.08  -0.045]


In [21]:
x = gausselimination_withpivot(n,P,q)
print(x)

[-0.045 -0.08  -0.105 -0.12  -0.125 -0.12  -0.105 -0.08  -0.045]


In [24]:
x = gausselimination_withoutpivot(n,P,q)
print(x)

[nan nan nan nan nan nan nan nan nan]


/tmp/ipykernel_275/3026029373.py:12: RuntimeWarning: invalid value encountered in scalar divide
  coe = -A[i][j]/A[j][j]
/tmp/ipykernel_275/3026029373.py:12: RuntimeWarning: divide by zero encountered in scalar divide
  coe = -A[i][j]/A[j][j]
/tmp/ipykernel_275/3026029373.py:14: RuntimeWarning: invalid value encountered in scalar multiply
  A[i][k]+=coe*A[j][k]


## 共役勾配法（Conjugate Gradient method）
$\mathrm{A}x = b$ を解くアルゴリズムを再掲します.

1. $x$の初期値 $x_{0}$、許容誤差 $\varepsilon$ を設定する

2. 残差 $r = b - \mathrm{A}x$ を計算する

3. 共役ベクトルを$p = r$とする

4. 誤差 $\mathrm{err} = \frac{\displaystyle ||r||_{2}}{\displaystyle ||b||_{2}}$ を計算する

5. $\mathrm{err}$ が $\varepsilon$ より大きい間以下を繰り返す

6. $\alpha = \frac{\displaystyle \left(p, r\right)}{\displaystyle \left(p, \mathrm{A}p\right)}$ を計算する

7. $xを$ $x = x + \alpha p$ と更新する

8. $rを$ $r = r - \alpha \mathrm{A}p$ と更新する

9. $\beta = \frac{\displaystyle \left(r, \mathrm{A}p\right)}{\displaystyle \left(p, \mathrm{A}p\right)}$ を計算する

10. $p$ を $p = r - \beta p$ と更新する

11. $\mathrm{err} = \frac{\displaystyle ||r||_{2}}{\displaystyle ||b||_{2}}$ 計算する

12. 5.に戻る

アルゴリズム中で登場する $||\cdot||_{2}$, $\left(\cdot, \cdot\right)$はそれぞれ $L^{2}$ノルムと内積であり以下のように計算できます.

$||x||_{2} = \sqrt{\sum_{i=1}^{n} x_{i}^{2}} = \sqrt{x_{1}^{2} + x_{2}^{2} + \cdots + x_{n - 1}^{2} + x_{n}^{2}}$

$\left(x, y\right) = \sum_{i=1}^{n}x_{i}y_{i} = x_{1}y_{1} + x_{2}y_{2} + \cdots + x_{n - 1}y_{n - 1} + x_{n}y_{n}$ 

In [ ]:
x = gausselimination_withpivot(n,A,b)
print(x)

## 共役勾配法を実装するための関数群

共役勾配法の実装にあたり以下の関数を使用して構いません。

In [15]:
import math
import numpy as np

# ベクトルxのL2ノルムを計算
def norm2(n, x):
    res = 0
    for i in range(n):
        res += x[i]**2
    res = math.sqrt(res)

    return res

# 行列Aとベクトルxの行列ベクトル積Axを計算
def matvec(n, A, x):
    res = np.zeros(n)
    for i in range(n):
        tmp = 0
        for j in range(n):
            tmp += A[i][j]*x[j]
        res[i] = tmp

    return res

# ベクトルxとベクトルyの内積を計算
def inner_product(n, x, y):
    res = 0
    for i in range(n):
        res += x[i]*y[i]

    return res

## 共役勾配法の雛形

In [18]:
import numpy as np

# 共役勾配法（CG法）でAx=bを解く
def CG(n, A, b):
    # 0で初期化
    x = np.zeros(n)
    # 残差の計算
    r = b - matvec(n, A, x)
    # 残差ベクトルの設定
    p = r.copy()

    # 許容誤差epsを設定
    eps = 10**-8
    # 誤差errを計算
    err = norm2(n, r)/norm2(n, b)

    counter = 0

    # 誤差errが許容誤差epsより大きい間以下を繰り返す
    while (err > eps):
      # ここを編集する
      Ap = matvec(n,A,p)
      alpha = inner_product(n,p,r) / inner_product(n,p,Ap)
      x += alpha * p
      r -= alpha * Ap
      beta = inner_product(n,r,Ap) / inner_product(n,p,Ap)
      p = r - beta * p
      print(f'Ap:{Ap},\talpha:{alpha},\tx:{x},\tr:{r},\tbeta:{beta},\tp:{p}')
      err = norm2(n, r) / norm2(n, b)
      counter += 1
      # print(err)
      # if counter > 1:
      #   break
    # 解を出力
    return x

## 共役勾配法で$Ax=b$を解く

In [19]:
x =  CG(n, A, b)
print(x)

Ap:[-1.  0.  0.  0.  0.  0.  0.  0. -1.],	alpha:0.4500000000000001,	x:[-0.045 -0.045 -0.045 -0.045 -0.045 -0.045 -0.045 -0.045 -0.045],	r:[ 0.35 -0.1  -0.1  -0.1  -0.1  -0.1  -0.1  -0.1   0.35],	beta:-3.500000000000001,	p:[ 0.   -0.45 -0.45 -0.45 -0.45 -0.45 -0.45 -0.45  0.  ]
Ap:[ 4.5 -4.5  0.   0.   0.   0.   0.  -4.5  4.5],	alpha:0.07777777777777777,	x:[-0.045 -0.08  -0.08  -0.08  -0.08  -0.08  -0.08  -0.08  -0.045],	r:[ 5.55111512e-17  2.50000000e-01 -1.00000000e-01 -1.00000000e-01
 -1.00000000e-01 -1.00000000e-01 -1.00000000e-01  2.50000000e-01
  5.55111512e-17],	beta:-0.5555555555555552,	p:[ 5.55111512e-17  1.11022302e-16 -3.50000000e-01 -3.50000000e-01
 -3.50000000e-01 -3.50000000e-01 -3.50000000e-01  1.11022302e-16
  5.55111512e-17]
Ap:[ 0.   3.5 -3.5  0.   0.   0.  -3.5  3.5  0. ],	alpha:0.07142857142857144,	x:[-0.045 -0.08  -0.105 -0.105 -0.105 -0.105 -0.105 -0.08  -0.045],	r:[ 5.55111512e-17 -5.55111512e-17  1.50000000e-01 -1.00000000e-01
 -1.00000000e-01 -1.00000000e-01  1.